Homepage edits
Team-Riscord/Harmony pull request #126
Opened 2024-03-18 18:53 UTC by ronakJain21

2024-03-18 19:12 UTC, aisaaxs requested changes

2024-03-18 19:12 UTC, aisaaxs commented on client/src/App.js
> +import Homepage from './component/Homepage/Homepage';
Please correct the Homepage path -> './components/Homepage/Homepage';

2024-03-18 19:12 UTC, aisaaxs commented on client/src/components/Homepage/Homepage.css
> +/* Homepage.css */
Please use the color palettte from the app icon to portray consistency in UI/UX elements.

The colors to be used are:
--oxford-blue: #01133Dff;
    --blue-green: rgb(11, 166, 209);
    --oxford-blue-2: #02113Aff;
    --oxford-blue-3: #030F36ff;
    --indigo-dye: #154A7Fff;
    --berkeley-blue: #072D53ff;
    --oxford-blue-4: #00204Bff;
    --oxford-blue-5: #01133Aff;
    --oxford-blue-6: #001943ff;
    --oxford-blue-7: #030C31ff;

2024-03-18 20:43 UTC, ronakJain21 commented on client/src/App.js
> +import Homepage from './component/Homepage/Homepage';
thank you for the correction

2024-03-19 11:18 UTC, aisaaxs commented
Can you please pull the changes from the development branch and create the Revised-Homepage branch based off of the dev branch? This way we can make sure that no conflicts arise whatsoever. Otherwise, the Homepage functions well and looks pretty good too. If possible, please redesign to match the colour palette of the app logo which is specified in the Signup and Login css files.

2024-03-19 11:50 UTC, closed without merging