Profile Component Functioning
Team-Riscord/Harmony pull request #212
Opened 2024-04-08 03:27 UTC by JacksonWilson99

all but image upload should be functioning

2024-04-08 05:19 UTC, aisaaxs requested changes

2024-04-08 05:19 UTC, aisaaxs commented on client/src/App.js
>            <Route path="/friendsList" element={<FriendsList />} />
Adding a path to a component will make it accessible to users just by going to the specific address. We need to integrate the component within the main app so it can only be accessed from within. But if you would like to use a path like this, then please make sure that users can't access the component without logging in first. This is not only for this component but others ones as well.

2024-04-08 05:19 UTC, aisaaxs commented on client/src/components/EditProfile/EditProfile.jsx
> +                    <img src={require('../../images' + userData.image)} alt='Profile' />
I may be wrong but I don't think there's a need for 'require' because the path is relative and is in the form of a string anyways. You can experiment with it and if it works, consider removing the keyword 'require'.

2024-04-08 05:19 UTC, aisaaxs commented on client/src/components/EditProfile/EditProfile.jsx
> +                        <input type="file" id="newProfile" accept="image/*"/>
You could limit the input to basic image file types like jpeg and png.

2024-04-08 05:19 UTC, aisaaxs commented on server/index.js
> +app.post("/updateData", (req, res) => {  // Route for updating userData variable in editProfile so it is up to date
Minor suggestion but consider naming this to 'updatedData' instead of 'updateDate' to imply that it's fetching data instead of editing it.

2024-04-08 05:19 UTC, aisaaxs commented on server/index.js
> +app.post("/updateData", (req, res) => {  // Route for updating userData variable in editProfile so it is up to date
Since it appears to be fetching data, consider turning it into a GET request instead.

2024-04-08 05:19 UTC, aisaaxs commented on server/index.js
> +  const editProfileQuery = 'UPDATE users SET username = ?, name = ?, bio = ? WHERE id = ?'; // Query for updating user information
As far as I remember, all table names should begin with a capital letter for consistency throughout the schema. So, this is either an error or you've changed the table name. If you have changed the table name, please consider reverting it to 'Users'.

2024-04-08 05:19 UTC, aisaaxs commented on client/src/components/EditProfile/EditProfile.jsx
> +            const response = await axios.post("http://localhost:8800/updateData", {id: userData.id});
Since this is fetching data, consider turning it into a GET request instead.

2024-04-08 05:19 UTC, aisaaxs commented on server/index.js
>    //checks if friend username exists
Everything looks good. Please go through the comments and suggestions and revise as you see fit. Also, please add the tests for this component in both integration test file and the unit test one that you have to make for this component. Thank you :)

2024-04-08 20:31 UTC, JacksonWilson99 commented on client/src/App.js
>            <Route path="/friendsList" element={<FriendsList />} />
Added alongside /dashboard in the isLoggedIn statement

2024-04-08 20:32 UTC, JacksonWilson99 commented on client/src/components/EditProfile/EditProfile.jsx
> +                    <img src={require('../../images' + userData.image)} alt='Profile' />
Wasn't displaying image without it, so will be keeping require

2024-04-08 20:35 UTC, JacksonWilson99 commented on client/src/components/EditProfile/EditProfile.jsx
> +                        <input type="file" id="newProfile" accept="image/*"/>
Done

2024-04-08 20:36 UTC, JacksonWilson99 commented on server/index.js
> +app.post("/updateData", (req, res) => {  // Route for updating userData variable in editProfile so it is up to date
Agreed, and done

2024-04-08 21:05 UTC, JacksonWilson99 commented on server/index.js
> +app.post("/updateData", (req, res) => {  // Route for updating userData variable in editProfile so it is up to date
In order to update the data properly I have to access the current Users.id stored in userData on the client side. I couldn't find a way to access it from index so this seemed like the logical route. If you have an alternative solution I would be open

2024-04-08 22:14 UTC, JacksonWilson99 commented on server/index.js
> +  const editProfileQuery = 'UPDATE users SET username = ?, name = ?, bio = ? WHERE id = ?'; // Query for updating user information
It worked with lowercase but I changed to Users for consistency's sake

2024-04-08 22:16 UTC, JacksonWilson99 commented on client/src/components/EditProfile/EditProfile.jsx
> +            const response = await axios.post("http://localhost:8800/updateData", {id: userData.id});
Same as the comment on index.js, I need to send information that I wasn't able to access on the server side, which I can't do in a get. If you have a solution otherwise I'm all ears

2024-04-08 22:17 UTC, JacksonWilson99 commented on server/index.js
>    //checks if friend username exists
Comments all finished. Will work on the image upload and tests while this is pending

2024-04-10 07:15 UTC, SoumilChhabra approved these changes
working perfectly :)

2024-04-10 07:16 UTC, merged